<?php

return [
    'default'         => env('DATABASE_DRIVER', 'mysql'),
    'connections'     => [
        'mysql' => [
            'type'            => 'mysql',
            'hostname'        => env('DB_HOST', 'db'),
            'database'        => env('DB_NAME', 'flipbook'),
            'username'        => env('DB_USER', 'root'),
            'password'        => env('DB_PASS', 'root'),
            'hostport'        => env('DB_PORT', '3306'),
            'charset'         => 'utf8mb4',
            'prefix'          => '',
            'deploy'          => 0,
            'rw_separate'     => false,
            'master_num'      => 1,
            'slave_no'        => '',
            'fields_strict'   => true,
            'break_reconnect' => false,
            'trigger_sql'     => true,
            'fields_cache'    => false,
        ],
        'pgsql' => [
            'type'            => 'pgsql',
            'hostname'        => env('DB_HOST', '127.0.0.1'),
            'database'        => env('DB_NAME', 'flipbook'),
            'username'        => env('DB_USER', 'postgres'),
            'password'        => env('DB_PASS', 'root'),
            'hostport'        => env('DB_PORT', '5432'),
            'charset'         => 'utf8',
            'prefix'          => '',
            'deploy'          => 0,
            'rw_separate'     => false,
            'master_num'      => 1,
            'slave_no'        => '',
            'fields_strict'   => true,
            'break_reconnect' => false,
            'trigger_sql'     => true,
            'fields_cache'    => false,
        ],
        'sqlite' => [
            'type'            => 'sqlite',
            'database'        => env('DB_PATH', app()->getRuntimePath() . 'flipbook.db'),
            'prefix'          => '',
            'fields_strict'   => true,
            'trigger_sql'     => true,
            'fields_cache'    => false,
        ],
    ],
];
